---
title: "Fantrax Report"
output:
  html_document:
    df_print: paged
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(tidyverse)

setwd("C:/Users/Joe/Documents/R")
df_MD <- read.csv("Fantrax_Data.csv", header = TRUE)
FTeams_MD <- read.csv("Fantrax_Agg_Data.csv", header = TRUE)

# rm(list=ls())
```

### Stats going into gameweek `r max(df_MD$GP)` 
***
#### Most favourable matchups
*sum total difference between each players league team position and their opponents league team position*

```{r, echo = FALSE, fig.height = 6, fig.width = 10}

ggplot(FTeams_MD, aes(x=reorder(Team, Total_PosDif, FUN=mean), Total_PosDif, fill=Team)) +
      geom_bar(stat="identity") + labs(x = "Teams", y = "Sum Table Difference") +
      geom_text(aes(label = round(Total_PosDif,2)), position=position_dodge(width=0.9), vjust=-0.25)
```

***
#### Best Squad (inc bench)
*Distribution of the FP.G of all 14 outfielders for each team*

```{r, echo = FALSE, fig.height = 6, fig.width = 10}

temp <- subset(df_MD, Status!= "W (Fri)" & Status!= "W (Sat)" & Status!= "W (Sun)" & 
                        Status!= "W (Mon)" & Status!= "W (Tue)" & Status!= "W (Wed)" &
                        Status!= "W (Thu)" & Status!= "FA")


p <- ggplot(temp, aes(x=reorder(Status, FP.G, FUN=mean), fill=Status,  y=FP.G))
p + geom_boxplot(coef = 5) + labs(x = "Teams", y = "FP.G")

```
